name: yeet
description: A dank and easy way to navigate using Router API of Navigator 2.0 -
  No boilerplate. No code generation. No classes. Just yeet!
version: 0.4.5
repository: https://github.com/HosseinYousefi/yeet

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.1
  path_to_regexp: ^0.4.0
  universal_platform: ^1.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.14.1+2
